import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http'
import { Observable, throwError } from 'rxjs';
import { catchError, retry } from 'rxjs/operators';
import { WeatherForecast } from './WeatherForecast';

@Injectable({
  providedIn: 'root'
})
export class WeatherService {

  constructor(private http: HttpClient) { }

   getCurrentWeather(): Observable<WeatherForecast[]> {
    return this.http.get<WeatherForecast[]>("https://localhost:44385/weatherforecast");
  }

}
// Generated by https://quicktype.io

